Server:
  Addr: 
  RunMode: release
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: ../logs
  LogFileName: app
  LogFileExt: .INFO
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  #MB,最大上传5MB的图片
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 192.168.1.25:3306
  DBName: blog_service 
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: suoyudong
  Issuser: blog-service
  Expire: 7200
Email:
  Host: 111.qq.com
  Port: 465
  UserName: xxx@qq.com
  Password: xxxxx
  IsSSL: true 
  From: xxxx@qq.com
  To: 
    - xxx@qq.com
