// Code generated by "stringer -linecomment -type ErrCode pkg/errcode/errcode.go"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERR_CODE_OK-200]
	_ = x[ERR_CODE_INVALID_PARAMS-400]
	_ = x[ERR_CODE_INTERNAL_ERROR-500]
	_ = x[ERR_CODE_NOT_FOUND_TOKEN-405]
}

const (
	_ErrCode_name_0 = "OK"
	_ErrCode_name_1 = "无效参数"
	_ErrCode_name_2 = "找不到token"
	_ErrCode_name_3 = "超时"
)

func (i ErrCode) String() string {
	switch {
	case i == 200:
		return _ErrCode_name_0
	case i == 400:
		return _ErrCode_name_1
	case i == 405:
		return _ErrCode_name_2
	case i == 500:
		return _ErrCode_name_3
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
